# General Settings
name: Chic Shine Cleaning
slogan: We love the job you don't!
email: kpardo@chicshinecleaning.com
phone: 404-790-8429
address: Marietta, GA
hours: "Mon-Fri: 9:00 am – 5:00 pm"
copyright: © 2016-2018 Chic Shine Cleaning.
favicon: /favicon.ico
twitter_handler: chicshine
analytics_code: UA-113148024-1
disqus: chicshine
disqus_url: chicshine.github.io
google_key: AIzaSyBNypSMIdwBvaE8fjCEVfAuqHbU19U2aWI

# Social Accounts
social_networks:
-  { name: facebook, url: 'https://www.facebook.com/ChicShineCleaning' }
-  { name: twitter, url: 'https://twitter.com/chicshine' }
-  { name: instagram, url: 'https://www.instagram.com/kgpardo/' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/karla-pardo-979b1498/' }
-  { name: skype, url: '' }
-  { name: github, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: 'https://www.pinterest.com/kgcosta/' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_authors: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages", "blog"]

# Outputting
permalink: /blog/:year/:month/:day/:title.html
category_dir: blog/categories
tag_dir: blog/tags

# Pagination
paginate: 10
paginate_path: "/blog/page-:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed